apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-closing-price-api
  labels:
    app: stock-closing-price-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-closing-price-api
  template:
    metadata:
      labels:
        app: stock-closing-price-api
    spec:
      containers:
      - name: stock-closing-price-api
        image: csuttles/stock-closing-price-api:0.0.1
        ports:
        - containerPort: 5000
        env:
        - name: NDAYS
          valueFrom:
            configMapKeyRef:
              name: stock-closing-price-api-env
              key: NDAYS
        - name: SYMBOL
          valueFrom:
            configMapKeyRef:
              name: stock-closing-price-api-env
              key: SYMBOL
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: stock-closing-price-api-env
